# SELF ATTENTION-MECHANISM WITH TRAINABLE WIEGHTS

In [ ]:
import torch

inputs = torch.tensor([
    [0.55, 0.87, 0.66],  # journey
    [0.57, 0.85, 0.64],  # starts
    [0.22, 0.58, 0.33],  # with
    [0.77, 0.25, 0.10],  # one
    [0.05, 0.80, 0.55]   # step
])

### Now we will move forward by making 3 variables

In [14]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2


### Now we will initiliase it by 3 weight matrics 

#### These matrices are key query and value matrices 

In [ ]:
torch.manual_seed(100)
# Note that we are setting requires_grad=False to reduce clutter in the outputs for illustration purposes.
# If we were to use the weight matrices for model training, we would set requires_grad=True to update these matrices during model training.
w_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)
w_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)
w_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)

In [16]:
print(w_key)

Parameter containing:
tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])


In [17]:
print(w_query)

Parameter containing:
tensor([[0.2627, 0.0428],
        [0.2080, 0.1180],
        [0.1217, 0.7356]])


In [18]:
print(w_value)

Parameter containing:
tensor([[0.7118, 0.7876],
        [0.4183, 0.9014],
        [0.9969, 0.7565]])


### Now we will compute the key, query and value matirce with the input

In [21]:
query_2 = x_2 @ w_query
key_2 = x_2 @ w_key
value_2 = x_2 @ w_value



In [ ]:
# As we can see based on the output for the query, this results in a 2-dimensional vector. 
# This is because: we set the number of columns of the corresponding weight matrix, via d_out, to 2:
print(query_2)

tensor([0.4044, 0.5955])


In [23]:
keys = inputs @ w_key
values = inputs @ w_value
queries = inputs @ w_query
print("keys.shape:", keys.shape)

print("values.shape:", values.shape)

print("queries.shape:", queries.shape)

keys.shape: torch.Size([5, 2])
values.shape: torch.Size([5, 2])
queries.shape: torch.Size([5, 2])


### Now we will compute our first attention score

In [25]:
keys_2 = keys[1] #A
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.1003)


In [26]:
attn_scores_2 = query_2 @ keys.T # All attention scores for given query
print(attn_scores_2)

tensor([1.1121, 1.1003, 0.5840, 0.5797, 0.7395])


In [27]:
attn_scores = queries @ keys.T # omega
print(attn_scores)

tensor([[1.1352, 1.1233, 0.5960, 0.5934, 0.7539],
        [1.1121, 1.1003, 0.5840, 0.5797, 0.7395],
        [0.5994, 0.5930, 0.3148, 0.3123, 0.3986],
        [0.3822, 0.3767, 0.2031, 0.1706, 0.2712],
        [0.8667, 0.8584, 0.4539, 0.4673, 0.5671]])


In [28]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)
print(d_k)

tensor([0.2418, 0.2399, 0.1665, 0.1660, 0.1858])
2


In [29]:
import torch

# Define the tensor
tensor = torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])

# Apply softmax without scaling
softmax_result = torch.softmax(tensor, dim=-1)
print("Softmax without scaling:", softmax_result)

# Multiply the tensor by 8 and then apply softmax
scaled_tensor = tensor * 8
softmax_scaled_result = torch.softmax(scaled_tensor, dim=-1)
print("Softmax after scaling (tensor * 8):", softmax_scaled_result)

Softmax without scaling: tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
Softmax after scaling (tensor * 8): tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


In [30]:
import numpy as np

# Function to compute variance before and after scaling
def compute_variance(dim, num_trials=1000):
    dot_products = []
    scaled_dot_products = []

    # Generate multiple random vectors and compute dot products
    for _ in range(num_trials):
        q = np.random.randn(dim)
        k = np.random.randn(dim)
        
        # Compute dot product
        dot_product = np.dot(q, k)
        dot_products.append(dot_product)
        
        # Scale the dot product by sqrt(dim)
        scaled_dot_product = dot_product / np.sqrt(dim)
        scaled_dot_products.append(scaled_dot_product)
    
    # Calculate variance of the dot products
    variance_before_scaling = np.var(dot_products)
    variance_after_scaling = np.var(scaled_dot_products)

    return variance_before_scaling, variance_after_scaling

# For dimension 5
variance_before_5, variance_after_5 = compute_variance(5)
print(f"Variance before scaling (dim=5): {variance_before_5}")
print(f"Variance after scaling (dim=5): {variance_after_5}")

# For dimension 20
variance_before_100, variance_after_100 = compute_variance(100)
print(f"Variance before scaling (dim=100): {variance_before_100}")
print(f"Variance after scaling (dim=100): {variance_after_100}")



Variance before scaling (dim=5): 4.88258260440093
Variance after scaling (dim=5): 0.9765165208801858
Variance before scaling (dim=100): 104.91507267076689
Variance after scaling (dim=100): 1.049150726707669


In [31]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([1.0942, 1.3495])
