# SELF ATTENTION-MECHANISM WITH TRAINABLE WIEGHTS

In [ ]:
import torch

inputs = torch.tensor([
    [0.55, 0.87, 0.66],  # journey
    [0.57, 0.85, 0.64],  # starts
    [0.22, 0.58, 0.33],  # with
    [0.77, 0.25, 0.10],  # one
    [0.05, 0.80, 0.55]   # step
])

### Now we will move forward by making 3 variables

In [14]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2


### Now we will initiliase it by 3 weight matrics 

#### These matrices are key query and value matrices 

In [ ]:
torch.manual_seed(100)
# Note that we are setting requires_grad=False to reduce clutter in the outputs for illustration purposes.
# If we were to use the weight matrices for model training, we would set requires_grad=True to update these matrices during model training.
w_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)
w_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)
w_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad= False)

In [16]:
print(w_key)

Parameter containing:
tensor([[0.1117, 0.8158],
        [0.2626, 0.4839],
        [0.6765, 0.7539]])


In [17]:
print(w_query)

Parameter containing:
tensor([[0.2627, 0.0428],
        [0.2080, 0.1180],
        [0.1217, 0.7356]])


In [18]:
print(w_value)

Parameter containing:
tensor([[0.7118, 0.7876],
        [0.4183, 0.9014],
        [0.9969, 0.7565]])


### Now we will compute the key, query and value matirce with the input

In [21]:
query_2 = x_2 @ w_query
key_2 = x_2 @ w_key
value_2 = x_2 @ w_value



In [ ]:
# As we can see based on the output for the query, this results in a 2-dimensional vector. 
# This is because: we set the number of columns of the corresponding weight matrix, via d_out, to 2:
print(query_2)

tensor([0.4044, 0.5955])


In [23]:
keys = inputs @ w_key
values = inputs @ w_value
queries = inputs @ w_query
print("keys.shape:", keys.shape)

print("values.shape:", values.shape)

print("queries.shape:", queries.shape)

keys.shape: torch.Size([5, 2])
values.shape: torch.Size([5, 2])
queries.shape: torch.Size([5, 2])


### Now we will compute our first attention score

In [25]:
keys_2 = keys[1] #A
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.1003)


In [26]:
attn_scores_2 = query_2 @ keys.T # All attention scores for given query
print(attn_scores_2)

tensor([1.1121, 1.1003, 0.5840, 0.5797, 0.7395])
